version: 0.0
os: linux

hooks:
  AfterInstall:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
  
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root